ls:
  .js: kebab-case
  .dir: kebab-case | point.case
  .vue: regex:([A-Z][a-z0-9]+){2,}
  src:
    .js: camelCase | kebab-case

  src/**/layouts:
    .vue: regex:([A-Z][a-z0-9]+){1,}Layout$

  src/**/views:
    .vue: regex:([A-Z][a-z0-9]+){1,}View$

  src/**/stores:
    .dir: camelCase
    .js: camelCase

ignore:
  - .git
  - node_modules
  - vite.config.js
